data_dir: './data/tts/'
api:
  port: 80
  host: '0.0.0.0'
  auth_token: '$API_AUTH_TOKEN|'
tgcalls:
  client:
    name: 'tgcalls-gate-client'
    api_id: 
    api_hash:
tts:
  data_dir: './data/tts/'
  torch_threads: 4
  use_cache: True
  langs:
    ru:
      provider: 'silero'
      model_file: 'v4_ru.pt'
      model_url: 'https://models.silero.ai/models/tts/ru/v4_ru.pt'
      speaker: 'kseniya'
      rate: 48000
    en:
      provider: 'silero'
      model_file: 'v3_en.pt'
      model_url: 'https://models.silero.ai/models/tts/en/v3_en.pt'
      speaker: 'en_1'
      rate: 48000

logging:
  version: 1
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(processName)s: %(process)d] [%(threadName)s: %(thread)d] [%(levelname)s] [%(name)s] %(filename)s:%(funcName)s:%(lineno)d - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    root:
      handlers:
      - console
      level: INFO
      propagate: false  
    fastapi:
      handlers:
      - console
      level: INFO
      propagate: false  
    uvicorn:
      handlers:
      - console
      level: INFO
      propagate: false